// ====================================================================
// Error codes for Mathematica link
// ====================================================================

#ifndef MATHEMATICA_ERROR_CODES_H
#define MATHEMATICA_ERROR_CODES_H

#include "mathematica_config.h"

#ifdef ENABLE_MATHLINK_H
#include <mathlink.h>
#else
#include <wstp.h>
#endif

namespace mathematica {

#ifdef ENABLE_MATHLINK_H
enum Error_codes : int {
   SUCCESS = MLEOK,
   DEAD_LINK = MLEDEAD,
   BAD_DATA = MLEGBAD,   
   OUT_OF_SEQUENCE_GET = MLEGSEQ,
   BAD_TOKEN = MLEPBTK,
   OUT_OF_SEQUENCE_PUT = MLEPSEQ,
   PUT_TOO_MUCH_DATA = MLEPBIG,
   OVERFLOW = MLEOVFL,
   OUT_OF_MEMORY = MLEMEM,
   DENIED_SOCKET = MLEACCEPT,
   UNCONNECTED = MLECONNECT,
   BAD_END_PACKET_CALL = MLEPUTENDPACKET,
   UNREAD_PACKET = MLENEXTPACKET,
   UNKNOWN_PACKET = MLEUNKNOWNPACKET,
   UNEXPECTED_END_PACKET = MLEGETENDPACKET,
   ABORTED_CALL = MLEABORT,
   CLOSED_CONNECTION = MLECLOSED,
   UNINITIALIZED_ENV = MLEINIT,
   INSUFFICIENT_ARGS = MLEARGV,
   UNAVAILABLE_PROTOCOL = MLEPROTOCOL,
   UNAVAILABLE_MODE = MLEMODE,
   UNSUPPORTED_LAUNCH = MLELAUNCH,
   NO_REPEATED_LAUNCH = MLELAUNCHAGAIN,
   NO_LAUNCH_SPACE = MLELAUNCHSPACE,
   NO_PARENT = MLENOPARENT,
   LINK_NAME_TAKEN = MLENAMETAKEN,
   LINK_NOT_LISTENING = MLENOLISTEN,
   BAD_LINK_NAME = MLEBADNAME,
   BAD_HOST = MLEBADHOST,
   LAUNCH_FAILED = MLELAUNCHFAILED,
   BAD_LAUNCH_NAME = MLELAUNCHNAME,
   CHAR_TO_LINK_ENC_FAIL = MLEPSCONVERT,
   LINK_TO_CHAR_ENC_FAIL = MLEGSCONVERT,
   BAD_DATA_ENC = MLEPDATABAD,
   NOT_EXECUTABLE = MLENOTEXE,
   FAILED_SYNC_OBJECT = MLESYNCOBJECTMAKE,
   BACK_OUT = MLEBACKOUT,
   UNRECOGNIZED_SYMBOL = MLEBADOPTSYM,
   UNRECOGNIZED_STRING = MLEBADOPTSTR,
   NEED_BIGGER_BUFFER = MLENEEDBIGGERBUFFER   
};
#else
enum Error_codes : int {
   SUCCESS = WSEOK,
   DEAD_LINK = WSEDEAD,
   BAD_DATA = WSEGBAD,   
   OUT_OF_SEQUENCE_GET = WSEGSEQ,
   BAD_TOKEN = WSEPBTK,
   OUT_OF_SEQUENCE_PUT = WSEPSEQ,
   PUT_TOO_MUCH_DATA = WSEPBIG,
   OVERFLOW = WSEOVFL,
   OUT_OF_MEMORY = WSEMEM,
   DENIED_SOCKET = WSEACCEPT,
   UNCONNECTED = WSECONNECT,
   BAD_END_PACKET_CALL = WSEPUTENDPACKET,
   UNREAD_PACKET = WSENEXTPACKET,
   UNKNOWN_PACKET = WSEUNKNOWNPACKET,
   UNEXPECTED_END_PACKET = WSEGETENDPACKET,
   ABORTED_CALL = WSEABORT,
   CLOSED_CONNECTION = WSECLOSED,
   UNINITIALIZED_ENV = WSEINIT,
   INSUFFICIENT_ARGS = WSEARGV,
   UNAVAILABLE_PROTOCOL = WSEPROTOCOL,
   UNAVAILABLE_MODE = WSEMODE,
   UNSUPPORTED_LAUNCH = WSELAUNCH,
   NO_REPEATED_LAUNCH = WSELAUNCHAGAIN,
   NO_LAUNCH_SPACE = WSELAUNCHSPACE,
   NO_PARENT = WSENOPARENT,
   LINK_NAME_TAKEN = WSENAMETAKEN,
   LINK_NOT_LISTENING = WSENOLISTEN,
   BAD_LINK_NAME = WSEBADNAME,
   BAD_HOST = WSEBADHOST,
   LAUNCH_FAILED = WSELAUNCHFAILED,
   BAD_LAUNCH_NAME = WSELAUNCHNAME,
   CHAR_TO_LINK_ENC_FAIL = WSEPSCONVERT,
   LINK_TO_CHAR_ENC_FAIL = WSEGSCONVERT,
   BAD_DATA_ENC = WSEPDATABAD,
   NOT_EXECUTABLE = WSENOTEXE,
   FAILED_SYNC_OBJECT = WSESYNCOBJECTMAKE,
   BACK_OUT = WSEBACKOUT,
   UNRECOGNIZED_SYMBOL = WSEBADOPTSYM,
   UNRECOGNIZED_STRING = WSEBADOPTSTR,
   NEED_BIGGER_BUFFER = WSENEEDBIGGERBUFFER
};
#endif

} // namespace mathematica

#endif
